//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RogueBasin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RogueBasin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ################################################################################
        ///################################################################################
        ///################################################################################
        ///#####.....................................................................######
        ///#####.....................................................................######
        ///#####..#################################################################..######
        ///#####..############# [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string battle {
            get {
                return ResourceManager.GetString("battle", resourceCulture);
            }
        }
        
        internal static byte[] becomeLich0 {
            get {
                object obj = ResourceManager.GetObject("becomeLich0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] burstofspeed0 {
            get {
                object obj = ResourceManager.GetObject("burstofspeed0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] burstofspeed1 {
            get {
                object obj = ResourceManager.GetObject("burstofspeed1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] burstofspeed2 {
            get {
                object obj = ResourceManager.GetObject("burstofspeed2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] closequarters0 {
            get {
                object obj = ResourceManager.GetObject("closequarters0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] cruelEnding0 {
            get {
                object obj = ResourceManager.GetObject("cruelEnding0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] crushLichGem0 {
            get {
                object obj = ResourceManager.GetObject("crushLichGem0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] deadFriendEnding0 {
            get {
                object obj = ResourceManager.GetObject("deadFriendEnding0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] enterDungeon0 {
            get {
                object obj = ResourceManager.GetObject("enterDungeon0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] enterDungeonAgain {
            get {
                object obj = ResourceManager.GetObject("enterDungeonAgain", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] enterDungeonAgain0 {
            get {
                object obj = ResourceManager.GetObject("enterDungeonAgain0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] evade0 {
            get {
                object obj = ResourceManager.GetObject("evade0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] evade1 {
            get {
                object obj = ResourceManager.GetObject("evade1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] forgetfulEnding0 {
            get {
                object obj = ResourceManager.GetObject("forgetfulEnding0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] forgetfulEndingDeadFriend0 {
            get {
                object obj = ResourceManager.GetObject("forgetfulEndingDeadFriend0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] helpFriend0 {
            get {
                object obj = ResourceManager.GetObject("helpFriend0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to DDRogue!
        ///
        ///A 7DRL by flend.
        ///
        ///
        ///What is your name?
        ///
        ///(This will load a saved game of that name.)
        ///(No unusual characters please!)
        ///.
        /// </summary>
        internal static string introPreamble {
            get {
                return ResourceManager.GetString("introPreamble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot exerpts and special move movies will be given throughout the
        ///game. If you&apos;ve already completed DDRogue a few times, you may wish to
        ///switch these off, but a new player should leave them on.
        ///.
        /// </summary>
        internal static string introSettings {
            get {
                return ResourceManager.GetString("introSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
        ///,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,^^^^,,,^^^^^^^,,^^^,,,,,,,,,,,,,,,,,,,,,,,,
        ///,,,,,,,,,,,,,,,,,,,,,,,,,,,,^^^^,,,,,^,,^^,,,^^,,,^^^^^^^,,,,,,,,,,,,,,,,,,,,,,,
        ///,,,,,,,,,,,,,,,,,,,,,,,,,,,,,^,,,,,,,^^^^^,,,,^^^^^,,^^^,,,,,,,,,,,,,,,,,,,,,,,,
        ///,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,^^,,,,,,^^^^^^^,,,^^,^^^^^,,,,,,,,,,,,,,,,,,,,,,,,
        ///,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,^^,^,^^^^^^^^,^^,,^,^^^^^,^,,,,,,,,,,,,,,,,,,,,,,,
        ///,,,,,,,,,,,,,,,,,,,, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string last {
            get {
                return ResourceManager.GetString("last", resourceCulture);
            }
        }
        
        internal static byte[] lichBattle0 {
            get {
                object obj = ResourceManager.GetObject("lichBattle0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] lichGem0 {
            get {
                object obj = ResourceManager.GetObject("lichGem0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] multiattack0 {
            get {
                object obj = ResourceManager.GetObject("multiattack0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] multiattack1 {
            get {
                object obj = ResourceManager.GetObject("multiattack1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] multiattack2 {
            get {
                object obj = ResourceManager.GetObject("multiattack2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] multiattack3 {
            get {
                object obj = ResourceManager.GetObject("multiattack3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] openspaceattack0 {
            get {
                object obj = ResourceManager.GetObject("openspaceattack0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] openspaceattack1 {
            get {
                object obj = ResourceManager.GetObject("openspaceattack1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] openspaceattack2 {
            get {
                object obj = ResourceManager.GetObject("openspaceattack2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] openspaceattack3 {
            get {
                object obj = ResourceManager.GetObject("openspaceattack3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] openspaceattack4 {
            get {
                object obj = ResourceManager.GetObject("openspaceattack4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] plotbackpack0 {
            get {
                object obj = ResourceManager.GetObject("plotbackpack0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] plotbadge0 {
            get {
                object obj = ResourceManager.GetObject("plotbadge0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] plotband0 {
            get {
                object obj = ResourceManager.GetObject("plotband0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] plotbook0 {
            get {
                object obj = ResourceManager.GetObject("plotbook0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] plotboots0 {
            get {
                object obj = ResourceManager.GetObject("plotboots0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] plotbracer0 {
            get {
                object obj = ResourceManager.GetObject("plotbracer0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] plotflint0 {
            get {
                object obj = ResourceManager.GetObject("plotflint0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] plotglassgem0 {
            get {
                object obj = ResourceManager.GetObject("plotglassgem0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] plotglove0 {
            get {
                object obj = ResourceManager.GetObject("plotglove0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] plotgreaves0 {
            get {
                object obj = ResourceManager.GetObject("plotgreaves0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] plotleadring0 {
            get {
                object obj = ResourceManager.GetObject("plotleadring0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] plotlockpicks0 {
            get {
                object obj = ResourceManager.GetObject("plotlockpicks0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] plotmedal0 {
            get {
                object obj = ResourceManager.GetObject("plotmedal0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] plotsash0 {
            get {
                object obj = ResourceManager.GetObject("plotsash0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] plotstone0 {
            get {
                object obj = ResourceManager.GetObject("plotstone0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] romanceEnding0 {
            get {
                object obj = ResourceManager.GetObject("romanceEnding0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] seeCorpses0 {
            get {
                object obj = ResourceManager.GetObject("seeCorpses0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] seeCorpsesForgetful0 {
            get {
                object obj = ResourceManager.GetObject("seeCorpsesForgetful0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] spotFriend0 {
            get {
                object obj = ResourceManager.GetObject("spotFriend0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] stunbox0 {
            get {
                object obj = ResourceManager.GetObject("stunbox0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] stunbox1 {
            get {
                object obj = ResourceManager.GetObject("stunbox1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] stunbox2 {
            get {
                object obj = ResourceManager.GetObject("stunbox2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] stunbox3 {
            get {
                object obj = ResourceManager.GetObject("stunbox3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] treasureRoom0 {
            get {
                object obj = ResourceManager.GetObject("treasureRoom0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] vaultbackstab0 {
            get {
                object obj = ResourceManager.GetObject("vaultbackstab0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] vaultbackstab1 {
            get {
                object obj = ResourceManager.GetObject("vaultbackstab1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] vaultbackstab2 {
            get {
                object obj = ResourceManager.GetObject("vaultbackstab2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] wallpush0 {
            get {
                object obj = ResourceManager.GetObject("wallpush0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] wallpush1 {
            get {
                object obj = ResourceManager.GetObject("wallpush1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] wallpush2 {
            get {
                object obj = ResourceManager.GetObject("wallpush2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] wallvault0 {
            get {
                object obj = ResourceManager.GetObject("wallvault0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] wallvault1 {
            get {
                object obj = ResourceManager.GetObject("wallvault1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] wallvault2 {
            get {
                object obj = ResourceManager.GetObject("wallvault2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] wallvault3 {
            get {
                object obj = ResourceManager.GetObject("wallvault3", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
